name: Testes Automatizados

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master 

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Configurar ambiente Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Instalar pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Executar testes
      run: |
        pytest  tests
